version: 0.2

phases:
        install:
                runtime-versions:
                        nodejs: 10
        pre-build:
                commands:
                        - echo pre-build
        build:
                commands:
                        -echo build
        post-build:
                commands:
                        -echo post-build
artifacts:
