version: 0.2

phases:
        install:
                runtime-versions:
                        nodejs: 12
                commands:
                        - touch .npmignore
                        - npm install -g gatsby
                        - apt-get install libpng-dev
        pre_build:
                commands:
                        - echo pre-build
                        - 'npm install'
                        - 'npm ci --production'
        build:
                commands:
                        - echo build
                        - 'npm run-script build'
        post_build:
                commands:
                        - echo post-build
                        - 'npm run-script deploy'
                        - aws s3 sync public/ s3://demo.meditateai.com --delete --acl public-read
artifacts:
        base-directory: public
        files:
                - '**/*'
        discard-paths: no
cache:
        paths:
                - '.cache/*'
                - 'public/*'
