version: 0.2

phases:
        install:
                runtime-versions:
                        nodejs: 10
        pre_build:
                commands:
                        - echo pre-build
        build:
                commands:
                        -echo build
        post_build:
                commands:
                        -echo post-build
